apiVersion: apps/v1
kind: Deployment
metadata:
  name: ork1-deployment
  namespace: ork
  labels:
    app: ork1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ork1
  template:
    metadata:
      labels:
        app: ork1
    spec:
      tolerations:
      - key: "scope"
        operator: "Equal"
        value: "ork"
        effect: "NoSchedule"
      nodeSelector:
        scope: ork
      containers:
      - name: ork
        image: tideorg/ork:dev
        imagePullPolicy: Always
        env:
        - name: Settings__Features__Metrics
          value: "true"
        - name: Settings__Features__Memory
          value: "true"
        - name: Settings__Features__Throttling
          value: "false"
        - name: Settings__Instance__Username
          value: "Ork-1"
        - name: Settings__Instance__SecretKey
          value: "AhDaAyMV+S5kqDA2GcNC1u9RIPFA0470RdxjEuEKjHhBgCQrsqR2Ik81gcSd06wIWoDH"
        - name: Settings__Instance__PrivateKey
          value: "CBHaP68zFuCHJHMpoNatSi1Ea43nJD2aN4hzznfRaF9epxsm/Ly4U1koay26BJ2KYbUBXTwV5sG7XbJh8Fi/e3AO1S+fr9VPSm8oG2TIQZdntg7V50hkYj5pt/SsLsL3"
        resources:
          limits:
            memory: "400Mi"
            cpu: "500m"
        ports:
        - name: web
          containerPort: 80
