apiVersion: apps/v1
kind: Deployment
metadata:
  name: ork1-deployment
  labels:
    app: ork1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ork1
  template:
    metadata:
      labels:
        app: ork1
    spec:
      containers:
      - name: ork
        image: tideorg/ork:dev
        imagePullPolicy: Always
        env: 
        - name: Settings__Features__Memory
          value: "true"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
          - containerPort: 80
