apiVersion: apps/v1
kind: Deployment
metadata:
  name: ork2-deployment
  labels:
    app: ork2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ork2
  template:
    metadata:
      labels:
        app: ork2
    spec:
      tolerations:
      - key: "scope"
        operator: "Equal"
        value: "service"
        effect: "NoSchedule"
      containers:
      - name: ork
        image: tideorg/ork:dev
        imagePullPolicy: Always
        env: 
        - name: Settings__Features__Metrics
          value: "true"
        - name: Settings__Features__Memory
          value: "true"
        - name: Settings__Features__Throttling
          value: "false"
        - name: Settings__Instance__Username
          value: "Ork-1"
        - name: Settings__Instance__SecretKey
          value: "AhC9OpCHalVMzgDc8LAyky05IKY92xhE2SmmCJ1RgzC0hkgDMkVa8W0cdsB0/I/1hW7D"
        - name: Settings__Instance__PrivateKey
          value: "AOb+bNal/0M0bT4jFC0K6+YuEBwwR5nBMaps7kZR64JFKCrU63/BQWasFCgIlgtlSOv5jzQfMjFBfsud/veC0ljtUScANNgwqmitEl6ChDOSyWBzA57sFmWAX2pe8fGR"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - name: web
          containerPort: 80
