apiVersion: apps/v1
kind: Deployment
metadata:
  name: ork3-deployment
  labels:
    app: ork3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ork3
  template:
    metadata:
      labels:
        app: ork3
    spec:
      containers:
      - name: ork
        image: tideorg/ork:dev
        imagePullPolicy: Always
        env: 
        - name: Settings__Features__Metrics
          value: "true"
        - name: Settings__Features__Memory
          value: "true"
        - name: Settings__Instance__Username
          value: "Ork-1"
        - name: Settings__Instance__SecretKey
          value: "AhAsCWVibFkZUZyT6XkcaPi8IB4+NnKWF1vE9zemMgW09pCY3OgLZAmbZ/WsxVD5g3Jb"
        - name: Settings__Instance__PrivateKey
          value: "BZJrKMczqmkPfk1ACDFP/kvyxczUFNbgwIf4SMPW0WMf0vePtGU88MW25xtujo+1oF1XODIJ7DlJigcZTDBPbAtMkH6YU2CzcO3eG9K0YCkLY8j98ahpdNzf/DBHH2NI"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - name: web
          containerPort: 80
