apiVersion: apps/v1
kind: Deployment
metadata:
  name: ork3-deployment
  labels:
    app: ork3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ork3
  template:
    metadata:
      labels:
        app: ork3
    spec:
      containers:
      - name: ork
        image: tideorg/ork:dev
        imagePullPolicy: Always
        env: 
        - name: Settings__Features__Metrics
          value: "true"
        - name: Settings__Features__Memory
          value: "true"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - name: web
          containerPort: 80
