apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ork-metrics
  namespace: ork
  labels:
    release: metrics
spec:
  selector:
    matchLabels:
      app: srv-ork
  endpoints:
  - port: web
    path: /metrics-text
    interval: 5s    
