apiVersion: v1
kind: Service
metadata:
  name: ork-srv1
spec:
  selector:
    app: ork1-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ork-srv2
spec:
  selector:
    app: ork2-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ork-srv3
spec:
  selector:
    app: ork3-app
  ports:
  - port: 80
    targetPort: 80
