apiVersion: batch/v1
kind: Job
metadata:
  name: stress-job
spec:
  template:
    spec:
      containers:
      - name: stress
        image: tideorg/orkstress:latest
        imagePullPolicy: Always
        command: [ "k6", "run", "test.multipleDAuth.js" ]
      restartPolicy: Never
  backoffLimit: 4
